/* Bioimage Analysis 互動考題 — 題庫資料（中英雙語版）
 * Bilingual question bank.
 * type: "single" 單選 | "multi" 多選 | "tf" 是非
 * 單選 ans: "A"|"B"|"C"|"D"
 * 多選 ans: ["A","C"]
 * 是非 ans: "T"|"F"
 */
window.QUIZ_DATA = {
  bioimage: {
    label: "Bioimage Analysis 互動考題",
    label_en: "Bioimage Analysis Interactive Quiz",
    labels_en: {
      "核心分析流程": "Core Analysis Pipeline",
      "進階主題": "Advanced Topics",
      "Step 1：影像基礎 (Fundamentals)": "Step 1: Image Fundamentals",
      "Step 2：預處理與去噪 (Preprocessing)": "Step 2: Preprocessing & Denoising",
      "Step 3：去卷積 (Deconvolution)": "Step 3: Deconvolution",
      "Step 4：配準與拼接 (Registration)": "Step 4: Registration & Stitching",
      "Step 5：傳統分割 (Classical Segmentation)": "Step 5: Classical Segmentation",
      "Step 6：深度學習分割 (DL Segmentation)": "Step 6: Deep Learning Segmentation",
      "Step 7：AI 基礎模型 (Foundation Models)": "Step 7: AI Foundation Models",
      "Step 8：細胞追蹤 (Tracking)": "Step 8: Cell / Particle Tracking",
      "Step 9：量化與特徵 (Quantification)": "Step 9: Quantification & Features",
      "Advanced：3D 與多維分析": "Advanced: 3D & Multi-Dimensional",
      "Advanced：高內涵分析 (HCS)": "Advanced: High-Content Screening",
      "Advanced：數位病理 (Pathology)": "Advanced: Digital Pathology",
      "Advanced：工具比較與整合": "Advanced: Tools & Reproducibility"
    },
    subjects: {
      "核心分析流程": {
        "Step 1：影像基礎 (Fundamentals)": [
          {type:"single",
            stem:"OME 標準的軸序為何？", stem_en:"What is the OME standard axis order?",
            A:"XYZCT", A_en:"XYZCT", B:"TCZYX", B_en:"TCZYX",
            C:"CZYXT", C_en:"CZYXT", D:"ZYXTC", D_en:"ZYXTC",
            ans:"B",
            exp:"OME 規範採 TCZYX（時間、通道、Z、Y、X）。Fiji 預設 XYCZT 與此不同。",
            exp_en:"OME spec uses TCZYX (time, channel, Z, Y, X). Fiji's default XYCZT differs from this."},
          {type:"single",
            stem:"3D 共軛焦資料 XY = 0.21 µm、Z = 1.0 µm，未告知 segmenter anisotropy 會發生什麼？",
            stem_en:"3D confocal data with XY=0.21 µm, Z=1.0 µm — what happens if you don't tell the segmenter about anisotropy?",
            A:"沒事，模型自動處理", A_en:"Nothing — the model auto-handles it",
            B:"3D 細胞形狀會被嚴重扭曲（Z 方向被低估）", B_en:"3D cell shapes get badly distorted (under-measured in Z)",
            C:"報錯", C_en:"Throws an error",
            D:"速度變慢", D_en:"Just slower",
            ans:"B",
            exp:"未處理各向異性是 3D 影像最常見的 silent failure，分割結果在 Z 軸看起來「壓扁」。",
            exp_en:"Ignored anisotropy is the most common silent failure in 3D — cells appear flattened along Z."},
          {type:"single",
            stem:"病理 WSI (.svs/.ndpi) 最該用哪個讀檔工具？",
            stem_en:"Best reader for pathology WSI (.svs/.ndpi)?",
            A:"PIL.Image.open", A_en:"PIL.Image.open",
            B:"tifffile 整檔讀入", B_en:"tifffile read whole file",
            C:"OpenSlide 或 TiffSlide（金字塔分塊存取）", C_en:"OpenSlide or TiffSlide (pyramidal tiled access)",
            D:"scipy.io.imread", D_en:"scipy.io.imread",
            ans:"C",
            exp:"WSI 是金字塔影像，必須用支援多解析度分塊存取的工具，OpenSlide 與 TiffSlide 是標準。",
            exp_en:"WSI is pyramidal; you need a reader that supports multi-resolution tiled access — OpenSlide/TiffSlide are the standards."},
          {type:"multi",
            stem:"以下哪些是開放的 bioimage 檔案格式？（多選）",
            stem_en:"Which of the following are open bioimage formats? (Multiple)",
            A:"OME-TIFF", A_en:"OME-TIFF",
            B:"CZI", B_en:"CZI",
            C:"OME-Zarr (NGFF)", C_en:"OME-Zarr (NGFF)",
            D:"HDF5 / N5", D_en:"HDF5 / N5",
            ans:["A","C","D"],
            exp:"CZI 是 Zeiss 專有格式。OME-TIFF、OME-Zarr、HDF5/N5 都是開放格式。",
            exp_en:"CZI is proprietary (Zeiss). OME-TIFF, OME-Zarr, and HDF5/N5 are open."},
          {type:"tf",
            stem:"是非題：把 16-bit 顯微影像直接 astype(uint8) 後再分析是好習慣。",
            stem_en:"True/False: Casting 16-bit microscopy to uint8 before analysis is good practice.",
            ans:"F",
            exp:"會失去 99% 的動態範圍。分析請保留 16-bit，只在顯示時做對比拉伸。",
            exp_en:"You lose 99% of the dynamic range. Keep 16-bit for analysis; contrast-stretch only for display."},
          {type:"single",
            stem:"Bio-Formats 主要解決什麼問題？",
            stem_en:"What problem does Bio-Formats primarily solve?",
            A:"加速 PCA 運算", A_en:"Speed up PCA",
            B:"讀取上百種顯微鏡專有格式並提取元資料", B_en:"Read 150+ proprietary microscopy formats and extract metadata",
            C:"GPU 訓練", C_en:"GPU training",
            D:"壓縮影像", D_en:"Compress images",
            ans:"B",
            exp:"Bio-Formats 是 Java 寫的影像讀檔聖物，支援 ~150 種廠商格式並保留 OME-XML 元資料。",
            exp_en:"Bio-Formats is the Java holy grail of microscopy I/O, supporting ~150 vendor formats and preserving OME-XML metadata."},
          {type:"single",
            stem:"OME-Zarr 相對於 OME-TIFF 的最大優勢？",
            stem_en:"Biggest advantage of OME-Zarr over OME-TIFF?",
            A:"檔案更小", A_en:"Smaller files",
            B:"雲端原生、分塊隨機存取、原生多解析度金字塔", B_en:"Cloud-native, chunked random access, native multi-resolution pyramid",
            C:"支援更多顏色", C_en:"More colors",
            D:"沒有優勢", D_en:"No advantage",
            ans:"B",
            exp:"OME-Zarr 為 NGFF 標準的雲端實作，特別適合 TB 級資料與遠端存取。",
            exp_en:"OME-Zarr is the cloud implementation of NGFF — ideal for TB-scale data and remote access."},
          {type:"single",
            stem:"什麼是 MPP？",
            stem_en:"What is MPP?",
            A:"Maximum pixel power", A_en:"Maximum pixel power",
            B:"Microns Per Pixel — 物理像素大小", B_en:"Microns Per Pixel — the physical pixel size",
            C:"Multi-channel Phase Plot", C_en:"Multi-channel Phase Plot",
            D:"一種 GPU", D_en:"A type of GPU",
            ans:"B",
            exp:"MPP 是病理 WSI 最關鍵的 metadata，pretrained 模型常綁定特定 MPP（20×=0.5、40×=0.25）。",
            exp_en:"MPP is the most critical WSI metadata; pretrained models often expect a specific MPP (20×=0.5, 40×=0.25)."},
          {type:"tf",
            stem:"是非題：所有顯微鏡格式都能透過 numpy.load 直接讀。",
            stem_en:"True/False: All microscopy formats can be loaded directly with numpy.load.",
            ans:"F",
            exp:"numpy.load 只讀 .npy/.npz。專有格式需 Bio-Formats / bioio / OpenSlide 等專屬工具。",
            exp_en:"numpy.load only reads .npy/.npz. Proprietary formats need Bio-Formats / bioio / OpenSlide."},
          {type:"single",
            stem:"BIDS-Microscopy 的主要目的？",
            stem_en:"Main purpose of BIDS-Microscopy?",
            A:"加速 GPU 推論", A_en:"Speed up GPU inference",
            B:"標準化顯微影像資料集的目錄結構與元資料", B_en:"Standardize directory structure and metadata for microscopy datasets",
            C:"訓練 DL 模型", C_en:"Train DL models",
            D:"壓縮資料", D_en:"Compress data",
            ans:"B",
            exp:"BIDS-Microscopy 是 BIDS 在影像領域的延伸，目標是讓資料集可共享、可重現。",
            exp_en:"BIDS-Microscopy extends BIDS to imaging — for shareable, reproducible datasets."}
        ],
        "Step 2：預處理與去噪 (Preprocessing)": [
          {type:"single",
            stem:"用 Gaussian filter 之前最該考慮的問題？",
            stem_en:"What's the top concern before applying a Gaussian filter?",
            A:"GPU 是否可用", A_en:"GPU availability",
            B:"濾波是否會干擾後續強度量化", B_en:"Whether filtering will bias downstream intensity quantification",
            C:"影像大小", C_en:"Image size",
            D:"螢光波長", D_en:"Fluorescence wavelength",
            ans:"B",
            exp:"Gaussian 會降低訊號峰值並影響共定位係數，量化前應慎用。",
            exp_en:"Gaussian filtering lowers peaks and biases colocalization — be cautious before quantification."},
          {type:"single",
            stem:"hot pixels（孤立白點）最快的去除方式？",
            stem_en:"Fastest way to remove hot pixels (isolated bright dots)?",
            A:"大半徑 Gaussian", A_en:"Large-radius Gaussian",
            B:"小半徑 median filter（如 radius=1–2）", B_en:"Small-radius median filter (radius 1–2)",
            C:"Rolling ball", C_en:"Rolling ball",
            D:"DL 模型", D_en:"DL model",
            ans:"B",
            exp:"Median 對孤立極值最有效且幾乎不影響周邊訊號。",
            exp_en:"Median is the textbook fix for isolated outliers with minimal collateral damage."},
          {type:"single",
            stem:"96-well HCS 每張影像中央亮、邊角暗。最佳工具？",
            stem_en:"96-well HCS image bright in centre, dim at corners. Best tool?",
            A:"BaSiC 平場校正（多張聯合估出 flatfield）", A_en:"BaSiC flat-field correction (joint estimation across batch)",
            B:"Single-image Gaussian", B_en:"Single-image Gaussian",
            C:"PCA 降維", C_en:"PCA",
            D:"訓練自己的 DL", D_en:"Train your own DL",
            ans:"A",
            exp:"BaSiC 設計就是處理 tile-scan / HCS 的平場與暗場校正。",
            exp_en:"BaSiC was designed exactly for tile-scan / HCS flatfield/darkfield correction."},
          {type:"single",
            stem:"Rolling-ball 半徑該怎麼設？",
            stem_en:"How to set the rolling-ball radius?",
            A:"愈大愈好", A_en:"As large as possible",
            B:"設成最大前景物件直徑的約 1.5 倍", B_en:"Roughly 1.5× the largest foreground object diameter",
            C:"愈小愈好", C_en:"As small as possible",
            D:"固定為 100 px", D_en:"Always 100 px",
            ans:"B",
            exp:"半徑太小會把細胞當背景減掉；太大保留不均背景。1.5× 物件直徑是經驗法則。",
            exp_en:"Too small erodes signal; too large leaves uneven background. 1.5× object diameter is the rule of thumb."},
          {type:"single",
            stem:"Noise2Void 的核心假設？",
            stem_en:"Core assumption of Noise2Void?",
            A:"像素間雜訊獨立", A_en:"Pixel-wise independent noise",
            B:"必須有 clean ground-truth 訓練配對", B_en:"Requires clean GT pairs",
            C:"需要 GPU 才能運作", C_en:"Requires GPU to work",
            D:"輸入必須是 8-bit", D_en:"Input must be 8-bit",
            ans:"A",
            exp:"N2V 假設像素間雜訊獨立、訊號相關。對結構化雜訊（stripe、固定花紋）會失效。",
            exp_en:"N2V assumes pixel-independent, signal-correlated noise. Fails on structured noise (stripes, fixed pattern)."},
          {type:"multi",
            stem:"以下哪些是「自監督」去噪方法？（多選）",
            stem_en:"Which of these are 'self-supervised' denoising methods? (Multiple)",
            A:"Noise2Void", A_en:"Noise2Void",
            B:"Noise2Noise", B_en:"Noise2Noise",
            C:"Noise2Self", C_en:"Noise2Self",
            D:"CARE", D_en:"CARE",
            ans:["A","B","C"],
            exp:"CARE 需要 clean GT，屬於 supervised。N2V/N2N/N2S 都屬於自監督家族。",
            exp_en:"CARE needs clean GT (supervised). N2V/N2N/N2S are the self-supervised family."},
          {type:"single",
            stem:"Cellpose 3 的「restoration」最特別之處？",
            stem_en:"What's special about Cellpose 3 restoration?",
            A:"只能 denoise", A_en:"Denoise only",
            B:"一鍵 denoise / deblur / upsample，可與分割整合", B_en:"One-click denoise / deblur / upsample, integrated with segmentation",
            C:"需要訓練自己的模型", C_en:"Requires training your own model",
            D:"只支援 2D", D_en:"2D only",
            ans:"B",
            exp:"Cellpose 3 (2025) 提供 denoise/deblur/upsample 三合一還原器，可在分割前直接套用。",
            exp_en:"Cellpose 3 (2025) bundles denoise/deblur/upsample restorers usable in a single segmentation call."},
          {type:"tf",
            stem:"是非題：濾波前後對量化共定位係數沒影響。",
            stem_en:"True/False: Filtering has no effect on quantitative colocalization coefficients.",
            ans:"F",
            exp:"濾波會改變峰值與背景結構，直接影響 Pearson/Manders。任意濾波會破壞共定位的可比性。",
            exp_en:"Filtering alters peaks and background structure, directly biasing Pearson/Manders. Casual filtering breaks colocalization comparability."},
          {type:"single",
            stem:"以下何者不是雜訊來源？",
            stem_en:"Which is NOT a noise source in microscopy?",
            A:"Poisson shot noise", A_en:"Poisson shot noise",
            B:"Read noise (Gaussian)", B_en:"Gaussian read noise",
            C:"Dark current", C_en:"Dark current",
            D:"Voxel anisotropy", D_en:"Voxel anisotropy",
            ans:"D",
            exp:"Voxel anisotropy 是空間取樣問題，不是雜訊。",
            exp_en:"Voxel anisotropy is a spatial-sampling issue, not noise."},
          {type:"single",
            stem:"建議的預處理順序是？",
            stem_en:"Recommended preprocessing order?",
            A:"DL denoise → 分割 → 平場校正", A_en:"DL denoise → segmentation → flat-field",
            B:"dark-frame → flat-field → hot-pixel median → 視需要 DL denoise → 量化", B_en:"dark-frame → flat-field → hot-pixel median → DL denoise if needed → quantify",
            C:"先轉 8-bit", C_en:"Convert to 8-bit first",
            D:"先 Gaussian σ=10", D_en:"Gaussian σ=10 first",
            ans:"B",
            exp:"由低層硬體校正到高層內容還原是合理順序。",
            exp_en:"From low-level hardware correction to high-level content restoration is the canonical order."}
        ],
        "Step 3：去卷積 (Deconvolution)": [
          {type:"single",
            stem:"什麼是 PSF？", stem_en:"What is a PSF?",
            A:"Pixel Subtraction Function", A_en:"Pixel Subtraction Function",
            B:"Point Spread Function — 顯微鏡將點光源擴散成的模糊斑", B_en:"Point Spread Function — the blurred image a microscope makes of a point source",
            C:"Photon Saturation Factor", C_en:"Photon Saturation Factor",
            D:"Pixel Sampling Frequency", D_en:"Pixel Sampling Frequency",
            ans:"B",
            exp:"PSF 是顯微系統的「特徵模糊形狀」，是去卷積的核心。",
            exp_en:"The PSF is the microscope's characteristic blur shape — the heart of deconvolution."},
          {type:"single",
            stem:"Richardson-Lucy 過度迭代（如 200 iter）會發生什麼？",
            stem_en:"What happens if you run Richardson-Lucy too long (e.g., 200 iter)?",
            A:"分割品質更高", A_en:"Better segmentation",
            B:"雜訊放大成 ringing 與 speckle", B_en:"Noise amplifies into ringing and speckle",
            C:"沒影響", C_en:"No effect",
            D:"報錯", D_en:"Throws an error",
            ans:"B",
            exp:"RL 的經典陷阱：後期迭代會把雜訊放大成偽訊號，10–30 iter 為經驗值。",
            exp_en:"Classic RL pitfall: late iterations amplify noise into artefacts; 10–30 iter is the empirical sweet spot."},
          {type:"single",
            stem:"哪種顯微術式從 3D 去卷積獲益最多？",
            stem_en:"Which modality benefits MOST from 3D deconvolution?",
            A:"STED", A_en:"STED",
            B:"SMLM (STORM)", B_en:"SMLM (STORM)",
            C:"Widefield 3D（離焦光嚴重）", C_en:"Widefield 3D (severe out-of-focus haze)",
            D:"2D phase contrast", D_en:"2D phase contrast",
            ans:"C",
            exp:"Widefield 沒有共軛焦的針孔濾離焦光，3D decon 可大幅提升銳度。",
            exp_en:"Widefield lacks the confocal pinhole; 3D decon dramatically sharpens it."},
          {type:"single",
            stem:"理論 PSF（如 Born-Wolf）何時失效？",
            stem_en:"When does a theoretical PSF (e.g., Born-Wolf) fail?",
            A:"高 NA 油鏡深入水樣本", A_en:"High-NA oil objective imaging deep in aqueous sample",
            B:"標準 air objective 拍乾樣本", B_en:"Standard air objective on a dry sample",
            C:"低倍率", C_en:"Low magnification",
            D:"完全不會失效", D_en:"Never fails",
            ans:"A",
            exp:"折射率失配 (oil ↔ water) 使球差變大，理論 PSF 不準，需測 bead PSF。",
            exp_en:"Refractive-index mismatch (oil ↔ water) causes spherical aberration; measure with beads instead."},
          {type:"single",
            stem:"在 widefield 上做去卷積前最該做的步驟？",
            stem_en:"Step you should take BEFORE deconvolving a widefield image?",
            A:"轉 8-bit", A_en:"Convert to 8-bit",
            B:"背景減除（去除離焦光低頻）", B_en:"Background subtract (remove low-frequency haze)",
            C:"直接送 segmentation", C_en:"Go straight to segmentation",
            D:"Gaussian smooth", D_en:"Gaussian smooth",
            ans:"B",
            exp:"離焦霧不扣會被 decon 「銳化」成偽訊號。",
            exp_en:"Unsubtracted haze gets sharpened into pseudo-signal by decon."},
          {type:"tf",
            stem:"是非題：CARE / DL decon 不需要 PSF 也能還原。",
            stem_en:"True/False: CARE / DL decon can restore without a PSF.",
            ans:"T",
            exp:"CARE 從成對的 low-SNR / high-SNR 影像直接學對映，不需顯式 PSF。",
            exp_en:"CARE learns the noisy→clean mapping from paired data without needing an explicit PSF."},
          {type:"single",
            stem:"Wiener filter 與 Richardson-Lucy 的主要差異？",
            stem_en:"Main difference between Wiener and Richardson-Lucy?",
            A:"Wiener 線性、無迭代；RL 非線性、迭代最大概似", A_en:"Wiener: linear, non-iterative; RL: nonlinear, iterative max-likelihood",
            B:"完全一樣", B_en:"Identical",
            C:"Wiener 用 GPU、RL 不能", C_en:"Wiener uses GPU, RL doesn't",
            D:"Wiener 適合 2D、RL 適合 3D", D_en:"Wiener is 2D, RL is 3D",
            ans:"A",
            exp:"Wiener 是 FFT 域線性還原；RL 是 Poisson 模型的迭代 ML 估計。",
            exp_en:"Wiener is linear FFT-domain restoration; RL is iterative MLE under a Poisson model."},
          {type:"multi",
            stem:"哪些是 RL 迭代次數過多的徵兆？（多選）",
            stem_en:"Which are signs of RL over-iteration? (Multiple)",
            A:"出現環狀 ringing artifact", A_en:"Ringing artefacts appear",
            B:"雜訊明顯放大", B_en:"Noise visibly amplified",
            C:"MSE 開始上升", C_en:"MSE starts rising",
            D:"細胞變得更銳利且雜訊降低", D_en:"Cells become sharper with less noise",
            ans:["A","B","C"],
            exp:"D 是正常迭代範圍的徵兆；其他 ABC 都是 over-iteration 的警訊。",
            exp_en:"D is what you want; A/B/C are over-iteration warnings."},
          {type:"single",
            stem:"PSFGenerator 用來做什麼？",
            stem_en:"What is PSFGenerator used for?",
            A:"算 Otsu 閾值", A_en:"Compute Otsu threshold",
            B:"從光學參數 (NA, λ, n) 計算理論 PSF", B_en:"Compute theoretical PSFs from optical parameters (NA, λ, n)",
            C:"訓練 DL 模型", C_en:"Train DL models",
            D:"壓縮影像", D_en:"Compress images",
            ans:"B",
            exp:"PSFGenerator (Fiji) 提供 Born-Wolf、Gibson-Lanni 等多種光學模型計算 PSF。",
            exp_en:"PSFGenerator (Fiji) computes PSFs from optical models (Born-Wolf, Gibson-Lanni, etc.)."},
          {type:"tf",
            stem:"是非題：去卷積後做強度量化（如螢光定量）是完全安全的。",
            stem_en:"True/False: It's perfectly safe to quantify intensity (e.g., fluorescence quantification) after deconvolution.",
            ans:"F",
            exp:"RL 不保線性，量化用建議改 Wiener 或加 TV 正則，並對所有條件用相同設定。",
            exp_en:"RL is not linearity-preserving; prefer Wiener or RL-TV with identical settings across conditions for quantification."}
        ],
        "Step 4：配準與拼接 (Registration)": [
          {type:"single",
            stem:"對齊 GFP 與 DAPI 通道（強度分佈差異大），最佳相似度指標？",
            stem_en:"Best similarity metric to align GFP and DAPI channels (very different intensity distributions)?",
            A:"Mutual Information", A_en:"Mutual Information",
            B:"SSD", B_en:"SSD",
            C:"Pearson", C_en:"Pearson",
            D:"L1", D_en:"L1",
            ans:"A",
            exp:"跨模態 / 跨通道用 MI 是經典做法。",
            exp_en:"MI is the canonical choice for cross-modal / cross-channel registration."},
          {type:"single",
            stem:"resample 一張 label image 應該用？",
            stem_en:"Resample a label image — which interpolator?",
            A:"Linear", A_en:"Linear",
            B:"Cubic", B_en:"Cubic",
            C:"Nearest neighbour", C_en:"Nearest neighbour",
            D:"Lanczos", D_en:"Lanczos",
            ans:"C",
            exp:"label 值代表 ID，不能被線性內插（會出現不存在的 ID）。",
            exp_en:"Label values are categorical IDs; linear interpolation creates nonexistent IDs."},
          {type:"single",
            stem:"處理 time-lapse stage drift，最簡單可靠的方法？",
            stem_en:"Simplest reliable method for time-lapse stage drift?",
            A:"B-spline 形變", A_en:"B-spline deformable",
            B:"Translation via phase correlation", B_en:"Translation via phase correlation",
            C:"SyN", C_en:"SyN",
            D:"手動標記", D_en:"Manual landmarks",
            ans:"B",
            exp:"純 drift 用平移即可，phase correlation 提供亞像素準確度。",
            exp_en:"Pure drift needs only translation; phase correlation gives subpixel accuracy."},
          {type:"single",
            stem:"哪個工具是 TB 級 light-sheet 拼接的事實標準？",
            stem_en:"Tool that is the de facto standard for TB-scale light-sheet stitching?",
            A:"BigStitcher", A_en:"BigStitcher",
            B:"ANTs", B_en:"ANTs",
            C:"OpenCV", C_en:"OpenCV",
            D:"PIL", D_en:"PIL",
            ans:"A",
            exp:"BigStitcher 為 light-sheet / 大型 tile 拼接設計，支援多視角融合與 N5/Zarr 儲存。",
            exp_en:"BigStitcher is built for light-sheet / large-tile stitching with multi-view fusion and N5/Zarr storage."},
          {type:"single",
            stem:"CLEM（光-電對齊）自動方法常失敗，建議用？",
            stem_en:"Auto methods fail on CLEM (light-EM). Recommended approach?",
            A:"Landmark + TPS (e.g., BigWarp)", A_en:"Landmark + TPS (e.g., BigWarp)",
            B:"Pure phase correlation", B_en:"Pure phase correlation",
            C:"Mutual information at full resolution", C_en:"Mutual information at full resolution",
            D:"放棄", D_en:"Give up",
            ans:"A",
            exp:"CLEM 影像模態差異極大，手選對應點 + TPS 是最穩定的方案。",
            exp_en:"CLEM modalities are too different; manual landmarks + TPS is the most reliable solution."},
          {type:"multi",
            stem:"以下哪些屬於剛體（rigid）變換的參數？（多選）",
            stem_en:"Which parameters belong to a rigid transform? (Multiple)",
            A:"Translation (dx, dy)", A_en:"Translation (dx, dy)",
            B:"Rotation", B_en:"Rotation",
            C:"Scaling", C_en:"Scaling",
            D:"Shearing", D_en:"Shearing",
            ans:["A","B"],
            exp:"剛體只有平移與旋轉。Scaling 屬 similarity，shearing 屬 affine。",
            exp_en:"Rigid = translation + rotation only. Scaling is similarity; shearing is affine."},
          {type:"tf",
            stem:"是非題：可以用 B-spline 校正 time-lapse drift，沒問題。",
            stem_en:"True/False: Using B-spline for time-lapse drift is fine.",
            ans:"F",
            exp:"過度參數化會 overfit，把真實生物結構也扭曲。drift 用 translation 就好。",
            exp_en:"Over-parameterization overfits and warps real biology. Use translation for drift."},
          {type:"single",
            stem:"多解析度金字塔配準 (multi-resolution pyramid) 的好處？",
            stem_en:"Benefit of multi-resolution pyramid registration?",
            A:"避免局部極值，加快收斂", A_en:"Avoids local minima and accelerates convergence",
            B:"完全不影響結果", B_en:"No effect on result",
            C:"只是節省記憶體", C_en:"Just saves memory",
            D:"必須關掉才能收斂", D_en:"Must be disabled to converge",
            ans:"A",
            exp:"先粗解析度找大致對齊，再細解析度精修。是優化器標配。",
            exp_en:"Coarse-to-fine prevents local minima and speeds convergence — a standard optimizer feature."},
          {type:"single",
            stem:"Stitcher 仰賴 stage 座標當初值，但 stage 寫的座標是垃圾，怎麼辦？",
            stem_en:"Stitcher seeds from stage coords but the microscope writes garbage. What to do?",
            A:"設為 regular grid，純從影像內容 refine", A_en:"Use regular grid mode and let the algorithm refine purely from image content",
            B:"改用 PIL", B_en:"Switch to PIL",
            C:"放棄拼接", C_en:"Give up stitching",
            D:"轉 8-bit", D_en:"Convert to 8-bit",
            ans:"A",
            exp:"BigStitcher / Grid stitching 都支援不信任 stage、純從影像 phase-correlation 算位置。",
            exp_en:"BigStitcher / Grid stitching can ignore stage and compute positions from image phase correlation alone."},
          {type:"single",
            stem:"ANTs SyN 演算法的主要特性？",
            stem_en:"Key property of the ANTs SyN algorithm?",
            A:"Linear only", A_en:"Linear only",
            B:"Symmetric diffeomorphic — 保證形變可逆", B_en:"Symmetric diffeomorphic — guarantees invertible deformation",
            C:"不能處理 3D", C_en:"Cannot handle 3D",
            D:"只有 GPU 版", D_en:"GPU-only",
            ans:"B",
            exp:"SyN 是 ANTs 招牌的對稱微分同胚變換，保證向前向後皆可逆，腦圖譜對齊標配。",
            exp_en:"SyN is ANTs' flagship symmetric diffeomorphic transform — invertible both ways; standard for brain atlas registration."}
        ],
        "Step 5：傳統分割 (Classical Segmentation)": [
          {type:"single",
            stem:"Otsu 假設前景與背景呈雙峰分佈。前景比例極小（&lt;5%）時會發生？",
            stem_en:"Otsu assumes bimodal distribution. What happens when foreground is very small (<5%)?",
            A:"閾值精確", A_en:"Threshold is accurate",
            B:"直方圖近似單峰，閾值飄移", B_en:"Histogram looks unimodal; threshold drifts",
            C:"完全沒影響", C_en:"No effect",
            D:"自動切換到 Li", D_en:"Auto-switches to Li",
            ans:"B",
            exp:"Otsu 雙峰假設失效時，可改試 Triangle 或 Li。",
            exp_en:"When Otsu's bimodality fails, try Triangle or Li."},
          {type:"single",
            stem:"watershed 一個細胞被切成 3 塊（over-segmentation）。最佳修正？",
            stem_en:"Watershed over-segments one cell into 3 pieces. Best fix?",
            A:"加大 Otsu 閾值", A_en:"Increase Otsu threshold",
            B:"平滑距離變換或加大 min_distance，減少假性 markers", B_en:"Smooth distance map or increase min_distance to reduce spurious markers",
            C:"換 Triangle", C_en:"Switch to Triangle",
            D:"用 8-bit", D_en:"Use 8-bit",
            ans:"B",
            exp:"過分割來自過多 markers，h-minima、Gaussian smooth distance、調 min_distance 都是標準修法。",
            exp_en:"Over-segmentation = too many markers. Smooth the distance map, use h-minima, or raise min_distance."},
          {type:"single",
            stem:"形態學 opening = ？",
            stem_en:"Morphological opening = ?",
            A:"Dilation 再 erosion", A_en:"Dilation then erosion",
            B:"Erosion 再 dilation", B_en:"Erosion then dilation",
            C:"距離變換", C_en:"Distance transform",
            D:"Gaussian + threshold", D_en:"Gaussian + threshold",
            ans:"B",
            exp:"Opening 標準定義是先 erosion 再 dilation，主要移除小亮點。",
            exp_en:"Opening is erosion then dilation — removes small bright specks."},
          {type:"single",
            stem:"距離變換 (distance transform) 後的「局部極大值」代表什麼？",
            stem_en:"Local maxima of the distance transform represent?",
            A:"細胞邊界", A_en:"Cell boundaries",
            B:"細胞中心", B_en:"Cell centres",
            C:"背景中心", C_en:"Background centres",
            D:"雜訊", D_en:"Noise",
            ans:"B",
            exp:"距離變換值在物件中心最高，作為 watershed markers 用。",
            exp_en:"The distance transform is highest at object centres — used as watershed markers."},
          {type:"tf",
            stem:"是非題：scikit-image 的 regionprops centroid 回傳順序是 (x, y)。",
            stem_en:"True/False: scikit-image regionprops centroid is (x, y).",
            ans:"F",
            exp:"是 (row, col) = (y, x)，這是常見陷阱。",
            exp_en:"It's (row, col) = (y, x) — a notorious trap."},
          {type:"single",
            stem:"adaptive thresholding (Sauvola/Niblack) 適合？",
            stem_en:"Adaptive thresholding (Sauvola/Niblack) is suited to?",
            A:"全域均勻照明", A_en:"Globally uniform illumination",
            B:"照明嚴重不均、無法平場校正時", B_en:"Severely uneven illumination when flat-field is unavailable",
            C:"二值影像", C_en:"Binary images",
            D:"DL pipeline", D_en:"DL pipeline",
            ans:"B",
            exp:"全域 Otsu 在不均照明下失效，local thresholding 是備案。",
            exp_en:"Global Otsu fails under uneven illumination; local thresholding is the fallback."},
          {type:"multi",
            stem:"以下哪些屬於形態學運算？（多選）",
            stem_en:"Which are morphological operations? (Multiple)",
            A:"Erosion", A_en:"Erosion",
            B:"Top-hat", B_en:"Top-hat",
            C:"Watershed", C_en:"Watershed",
            D:"PCA", D_en:"PCA",
            ans:["A","B","C"],
            exp:"Watershed 屬於形態學 / 拓撲方法。PCA 是統計降維。",
            exp_en:"Watershed is a morphological/topological method; PCA is statistical dimensionality reduction."},
          {type:"single",
            stem:"scikit-image 的 <code>try_all_threshold</code> 主要用途？",
            stem_en:"Main purpose of scikit-image's <code>try_all_threshold</code>?",
            A:"自動選最佳閾值", A_en:"Auto-pick the best threshold",
            B:"一次比對多種閾值法的視覺效果", B_en:"Visually compare multiple thresholding methods at once",
            C:"訓練 DL", D_en:"Train DL",
            C_en:"Train DL", D:"GPU 加速", D_en:"GPU acceleration",
            ans:"B",
            exp:"是探索性視覺工具，最終仍由分析者根據結果挑選。",
            exp_en:"Exploratory visual tool; the analyst still picks the final method."},
          {type:"single",
            stem:"h-minima 抑制 (h-minima suppression) 的作用？",
            stem_en:"What does h-minima suppression do?",
            A:"加深背景", A_en:"Deepen background",
            B:"消除淺局部極小值，減少 watershed 過分割", B_en:"Suppress shallow local minima, reducing watershed over-segmentation",
            C:"模糊邊緣", C_en:"Blur edges",
            D:"二值化", D_en:"Binarize",
            ans:"B",
            exp:"h-minima 把深度 < h 的局部極小值「填平」，避免它們被當成新 catchment basin。",
            exp_en:"h-minima floods local minima shallower than h so they are not treated as catchment basins."},
          {type:"tf",
            stem:"是非題：好的傳統分割流程通常不需要視覺檢查中間步驟。",
            stem_en:"True/False: A good classical pipeline usually doesn't need visual inspection at intermediate steps.",
            ans:"F",
            exp:"每個閾值與參數都該視覺檢查，否則 silent failure 累積到最後一發不可收。",
            exp_en:"Visually inspect every threshold and parameter; silent failures snowball if you don't."}
        ],
        "Step 6：深度學習分割 (DL Segmentation)": [
          {type:"single",
            stem:"密集圓核 (組織 DAPI) 分割首選？",
            stem_en:"Best default for densely packed round nuclei (tissue DAPI)?",
            A:"StarDist 2D_versatile_fluo", A_en:"StarDist 2D_versatile_fluo",
            B:"Omnipose", B_en:"Omnipose",
            C:"Mesmer", C_en:"Mesmer",
            D:"純 Otsu", D_en:"Pure Otsu",
            ans:"A",
            exp:"StarDist 的 star-convex 表示為密集圓核設計。",
            exp_en:"StarDist's star-convex representation is built for dense round nuclei."},
          {type:"single",
            stem:"Mesmer 規定通道順序 channel 0 = nucleus, channel 1 = membrane。如果顛倒呢？",
            stem_en:"Mesmer requires channel 0 = nucleus, channel 1 = membrane. What if you swap them?",
            A:"報錯", A_en:"Throws an error",
            B:"不報錯、分割結果完全錯誤 (silent failure)", B_en:"No error, completely wrong segmentation (silent failure)",
            C:"自動偵測修正", C_en:"Auto-corrects",
            D:"變更快", D_en:"Runs faster",
            ans:"B",
            exp:"模型按通道順序處理，順序錯誤就是 silent failure，常見錯誤。",
            exp_en:"The model treats channels by order; wrong order = silent failure. A common bug."},
          {type:"single",
            stem:"細菌 / 神經元等細長分支結構，最佳 DL 工具？",
            stem_en:"Best DL tool for elongated/branching shapes (bacteria, neurons)?",
            A:"Cellpose cyto3", A_en:"Cellpose cyto3",
            B:"Omnipose", B_en:"Omnipose",
            C:"StarDist", C_en:"StarDist",
            D:"Mesmer", D_en:"Mesmer",
            ans:"B",
            exp:"Omnipose 是 Cellpose 的姊妹模型，針對細長分支型態優化。",
            exp_en:"Omnipose is Cellpose's sister model tuned for elongated/branching morphologies."},
          {type:"single",
            stem:"nnU-Net 最大特色？", stem_en:"Biggest feature of nnU-Net?",
            A:"自配置 pipeline（自己決定預處理、架構、loss、學習率）", A_en:"Self-configuring pipeline (auto picks preprocessing, architecture, loss, lr)",
            B:"只能 2D", B_en:"2D only",
            C:"需要極少資料", C_en:"Needs almost no data",
            D:"不需 GPU", D_en:"No GPU needed",
            ans:"A",
            exp:"nnU-Net 是醫學影像 benchmark 事實標準，最大賣點就是自配置。",
            exp_en:"nnU-Net's signature is self-configuration — the de facto medical-imaging benchmark."},
          {type:"single",
            stem:"應如何評估分割結果？",
            stem_en:"How should you evaluate segmentation results?",
            A:"看訓練集眼睛覺得準", A_en:"Eyeball the training set",
            B:"在獨立測試集計算 IoU / Dice / AP", B_en:"Quantify IoU / Dice / AP on a held-out test set",
            C:"看 epoch 數", C_en:"Check epoch count",
            D:"看 GPU 用量", D_en:"Check GPU usage",
            ans:"B",
            exp:"視覺評估永遠樂觀，量化指標 + held-out 才可信。",
            exp_en:"Visual evaluation is always optimistic; metrics on held-out data are the only truth."},
          {type:"multi",
            stem:"以下哪些屬於「實例分割 (instance segmentation)」輸出？（多選）",
            stem_en:"Which are 'instance segmentation' outputs? (Multiple)",
            A:"Cellpose 梯度流場 → mask", A_en:"Cellpose flow field → mask",
            B:"StarDist star-convex 多邊形", B_en:"StarDist star-convex polygons",
            C:"U-Net 二元語意機率圖", C_en:"U-Net binary semantic probability map",
            D:"Mesmer per-cell label", D_en:"Mesmer per-cell labels",
            ans:["A","B","D"],
            exp:"純 U-Net 語意 mask 沒有個體 ID。其他三者直接給每個物件 ID。",
            exp_en:"Plain U-Net semantic masks have no per-object ID. The others give one ID per object."},
          {type:"single",
            stem:"AP@0.5 的意思？", stem_en:"What does AP@0.5 mean?",
            A:"平均精度，以 IoU = 0.5 為閾值判物件配對", A_en:"Average precision with IoU=0.5 as the matching threshold",
            B:"50% 準確率", B_en:"50% accuracy",
            C:"0.5 fps", C_en:"0.5 fps",
            D:"用 50 epoch", D_en:"50 epochs",
            ans:"A",
            exp:"AP@IoU 是物件層級指標，閾值決定預測物件何時與 GT 算配對。",
            exp_en:"AP@IoU is an object-level metric; the threshold decides when a prediction matches GT."},
          {type:"single",
            stem:"Cellpose 4 (Cellpose-SAM, 2025) 的 backbone 是？",
            stem_en:"Backbone of Cellpose 4 (Cellpose-SAM, 2025)?",
            A:"ResNet50", A_en:"ResNet50",
            B:"SAM transformer", B_en:"SAM transformer",
            C:"純 CNN", C_en:"Plain CNN",
            D:"RNN", D_en:"RNN",
            ans:"B",
            exp:"Cellpose 4 把 SAM ViT backbone 與 Cellpose 流場 head 結合。",
            exp_en:"Cellpose 4 combines a SAM ViT backbone with the Cellpose flow-field head."},
          {type:"tf",
            stem:"是非題：對所有任務都應該先嘗試從零訓練自己的模型。",
            stem_en:"True/False: For every task, start by training your own model from scratch.",
            ans:"F",
            exp:"先試 pretrained generalist (Cellpose-SAM cyto3, StarDist versatile)，大多數人不需自訓。",
            exp_en:"Try pretrained generalists first (Cellpose-SAM cyto3, StarDist versatile); most users never train."},
          {type:"single",
            stem:"Human-in-the-loop fine-tune 的優勢？",
            stem_en:"Advantage of human-in-the-loop fine-tuning?",
            A:"以少量互動標註逐步改善模型", A_en:"Iteratively improve the model with a small set of interactive labels",
            B:"完全免人工", B_en:"No human required",
            C:"自動跳過 GPU", C_en:"Skips the GPU automatically",
            D:"取代測試集", D_en:"Replaces a test set",
            ans:"A",
            exp:"Cellpose GUI 提供 human-in-the-loop 訓練流程，標、訓、修反覆。",
            exp_en:"Cellpose's GUI offers human-in-the-loop training: label, train, refine in cycles."}
        ],
        "Step 7：AI 基礎模型 (Foundation Models)": [
          {type:"single",
            stem:"SAM (Segment Anything) 開啟了什麼範式？",
            stem_en:"What paradigm did SAM open?",
            A:"提示式 (promptable) 分割", A_en:"Promptable segmentation",
            B:"純監督式分類", B_en:"Pure supervised classification",
            C:"GAN 影像生成", C_en:"GAN image generation",
            D:"自監督預訓練", D_en:"Self-supervised pretraining",
            ans:"A",
            exp:"SAM 接收 prompt（點 / box / mask / text）即時給對應 mask。",
            exp_en:"SAM accepts a prompt (point/box/mask/text) and instantly returns a mask."},
          {type:"single",
            stem:"分割 EM 影像最佳的 FM 選擇？",
            stem_en:"Best FM for EM image segmentation?",
            A:"原版 SAM", A_en:"Vanilla SAM",
            B:"Micro-SAM 的 vit_b_em / vit_l_em", B_en:"Micro-SAM's vit_b_em / vit_l_em",
            C:"UNI", C_en:"UNI",
            D:"CONCH", D_en:"CONCH",
            ans:"B",
            exp:"Micro-SAM 的 EM 變體在 EM 資料上做過特化微調。",
            exp_en:"Micro-SAM's EM variants are fine-tuned on EM data."},
          {type:"single",
            stem:"病理 FM (UNI, Virchow) 的輸出是？",
            stem_en:"Output of pathology FMs (UNI, Virchow)?",
            A:"分類標籤", A_en:"Classification labels",
            B:"細胞 mask", B_en:"Cell masks",
            C:"嵌入向量 (embeddings)，需搭配下游分類器", C_en:"Embeddings — pair with a downstream classifier",
            D:"染色正規化影像", D_en:"Stain-normalized images",
            ans:"C",
            exp:"病理 FM 是表徵學習，下游用 MIL / linear probe 接成預測。",
            exp_en:"Pathology FMs are representation learners; downstream MIL / linear probe yields predictions."},
          {type:"single",
            stem:"用 2D SAM 在 3D stack 上逐切片獨立跑，會發生？",
            stem_en:"Running 2D SAM slice-by-slice on a 3D stack — what happens?",
            A:"同一細胞跨 z 的 ID 不一致", A_en:"Inconsistent IDs for the same cell across z",
            B:"自動 3D 連結", B_en:"Auto-links into 3D",
            C:"報錯", C_en:"Throws an error",
            D:"更快", D_en:"Faster",
            ans:"A",
            exp:"2D 模型對每 slice 獨立預測，無法跨 z 維持 ID。要用 Micro-SAM volumetric / MedSAM2 / Cellpose 3D。",
            exp_en:"2D models predict each slice independently with no cross-z ID. Use Micro-SAM volumetric / MedSAM2 / Cellpose 3D instead."},
          {type:"single",
            stem:"CLAM (multiple instance learning) 用於？",
            stem_en:"CLAM (multiple instance learning) is used for?",
            A:"細胞分割", A_en:"Cell segmentation",
            B:"弱監督 slide-level 分類（只有 slide 標籤）", B_en:"Weakly-supervised slide-level classification (slide labels only)",
            C:"染色正規化", C_en:"Stain normalization",
            D:"3D 重建", D_en:"3D reconstruction",
            ans:"B",
            exp:"CLAM 把 slide 視為「instance bag」，由 attention 學哪些 patch 重要。",
            exp_en:"CLAM treats a slide as a bag of instances; attention learns which patches matter."},
          {type:"multi",
            stem:"以下哪些是「fine-tune 策略」？（多選）",
            stem_en:"Which are fine-tuning strategies? (Multiple)",
            A:"Linear probe", A_en:"Linear probe",
            B:"LoRA / Adapter", B_en:"LoRA / Adapter",
            C:"Full fine-tune", C_en:"Full fine-tune",
            D:"凍結整個模型不訓練", D_en:"Freeze everything (no training)",
            ans:["A","B","C"],
            exp:"D 不算 fine-tune；A/B/C 都是訓練不同子集參數的策略。",
            exp_en:"D is not fine-tuning. A/B/C are valid strategies training different parameter subsets."},
          {type:"single",
            stem:"SAM 2 比 SAM 多了什麼？",
            stem_en:"What does SAM 2 add over SAM?",
            A:"純 CPU 推論", A_en:"CPU-only inference",
            B:"影片 / 時序記憶 + Hiera backbone + 速度提升", B_en:"Video/temporal memory + Hiera backbone + faster",
            C:"3D 支援", C_en:"3D support",
            D:"沒新增什麼", D_en:"Nothing new",
            ans:"B",
            exp:"SAM 2 加入 memory attention 處理影片，比 SAM 快約 6×。",
            exp_en:"SAM 2 adds memory attention for video and runs ~6× faster than SAM."},
          {type:"tf",
            stem:"是非題：原版 SAM 對暗螢光、低 SNR 顯微影像表現極佳。",
            stem_en:"True/False: Vanilla SAM performs extremely well on low-contrast / low-SNR fluorescence microscopy.",
            ans:"F",
            exp:"原版 SAM 在 EM、低 SNR fluorescence、密集細胞表現有限，需 Micro-SAM 等微調。",
            exp_en:"Vanilla SAM struggles on EM, low-SNR fluorescence, and dense cells — use Micro-SAM or fine-tune."},
          {type:"single",
            stem:"DINOv2 在病理 FM 上的角色？",
            stem_en:"Role of DINOv2 in pathology FMs?",
            A:"提供自監督預訓練骨幹（UNI, Virchow 基於此）", A_en:"Provides self-supervised pretrained backbone (UNI, Virchow built on it)",
            B:"取代 OpenSlide", B_en:"Replaces OpenSlide",
            C:"染色正規化", C_en:"Stain normalization",
            D:"WSI 壓縮", D_en:"WSI compression",
            ans:"A",
            exp:"DINOv2 是自監督 ViT 訓練法，許多病理 FM (UNI / Virchow) 使用其架構與訓練範式。",
            exp_en:"DINOv2 is a self-supervised ViT training scheme; UNI / Virchow build on it."},
          {type:"single",
            stem:"BioImage Model Zoo 解決什麼問題？",
            stem_en:"What problem does BioImage Model Zoo solve?",
            A:"跨工具 (Fiji, ilastik, deepImageJ, QuPath) 共享預訓練模型", A_en:"Share pretrained models across tools (Fiji, ilastik, deepImageJ, QuPath)",
            B:"訓練 GPT 模型", B_en:"Train GPT models",
            C:"取代 GitHub", C_en:"Replace GitHub",
            D:"染色正規化", D_en:"Stain normalization",
            ans:"A",
            exp:"Model Zoo 提供標準化格式，讓同一模型可在多種 bioimage 工具中運行。",
            exp_en:"The Model Zoo defines a standard format so one model runs across many bioimage tools."}
        ],
        "Step 8：細胞追蹤 (Tracking)": [
          {type:"single",
            stem:"5% 分割漏失常造成多少 ID switch？（量級）",
            stem_en:"A 5% detection miss causes roughly how many ID switches?",
            A:"5%", A_en:"5%",
            B:"&lt;1%", B_en:"<1%",
            C:"~30%", C_en:"~30%",
            D:"0", D_en:"0",
            ans:"C",
            exp:"漏偵測會放大成 ID switch，這就是「先優化分割再調 tracker」的道理。",
            exp_en:"Detection misses amplify into ID switches — hence 'optimize segmentation before tracker'."},
          {type:"single",
            stem:"研究細胞分裂譜系最適合？",
            stem_en:"Best tracker for division lineages?",
            A:"btrack（Bayesian + 明確建模 division）", A_en:"btrack (Bayesian + explicit division)",
            B:"nearest neighbour", B_en:"Nearest neighbour",
            C:"Pure Kalman", C_en:"Pure Kalman",
            D:"phase correlation", D_en:"Phase correlation",
            ans:"A",
            exp:"btrack 明確處理 mother→daughter 拓撲，譜系研究的事實首選。",
            exp_en:"btrack explicitly handles mother→daughter topology — the lineage default."},
          {type:"single",
            stem:"Trackastra (2024 ECCV) 是哪一類追蹤模型？",
            stem_en:"Trackastra (2024 ECCV) is what kind of tracker?",
            A:"Hungarian linker only", A_en:"Hungarian linker only",
            B:"Transformer-based 聯合偵測-追蹤", B_en:"Transformer-based joint detection-tracking",
            C:"純 Kalman", C_en:"Pure Kalman",
            D:"純最近鄰", D_en:"Pure nearest neighbour",
            ans:"B",
            exp:"Trackastra 用 transformer 學跨幀關聯，2024 Cell Tracking Challenge 冠軍。",
            exp_en:"Trackastra learns cross-frame associations with transformers — won the 2024 CTC."},
          {type:"single",
            stem:"LAP (Linear Assignment Problem) 是什麼？",
            stem_en:"What is the LAP (Linear Assignment Problem)?",
            A:"配對問題，用 Hungarian 等演算法求全域最佳", A_en:"Matching problem solved globally by Hungarian-type algorithms",
            B:"線性 PCA", B_en:"Linear PCA",
            C:"GPU 架構", C_en:"GPU architecture",
            D:"濾波器", D_en:"A filter",
            ans:"A",
            exp:"Jaqaman 2008 把粒子追蹤建成 LAP，是 TrackMate 的核心 linker。",
            exp_en:"Jaqaman 2008 framed tracking as LAP — the linker behind TrackMate."},
          {type:"single",
            stem:"Gap closing 在 tracker 的作用？",
            stem_en:"What does gap closing do in a tracker?",
            A:"連接短暫漏偵測（middle frames）形成的軌跡斷裂", A_en:"Reconnect tracks broken by short detection misses in intermediate frames",
            B:"放大細胞", B_en:"Enlarge cells",
            C:"清除背景", C_en:"Remove background",
            D:"配色 trick", D_en:"A color trick",
            ans:"A",
            exp:"短暫漏偵測會把軌跡切斷成兩段，gap closing 把它們重新接起。",
            exp_en:"A short miss splits a track in two; gap closing reconnects them."},
          {type:"multi",
            stem:"以下哪些是 Cell Tracking Challenge 指標？（多選）",
            stem_en:"Which are Cell Tracking Challenge metrics? (Multiple)",
            A:"DET", A_en:"DET",
            B:"SEG", B_en:"SEG",
            C:"TRA", C_en:"TRA",
            D:"BLAST", D_en:"BLAST",
            ans:["A","B","C"],
            exp:"BLAST 是序列比對工具，與影像追蹤無關。",
            exp_en:"BLAST is for sequences, not tracking."},
          {type:"single",
            stem:"視覺檢查影片「看起來追得對」可不可以取代量化評估？",
            stem_en:"Can 'looks right by eye' replace quantitative tracking evaluation?",
            A:"可以", A_en:"Yes",
            B:"不行，必須用標註 GT 算 TRA/DET", B_en:"No — quantify TRA/DET on GT",
            C:"只要 60 fps 就可以", C_en:"OK if it's 60 fps",
            D:"短片可以、長片不行", D_en:"OK for short clips",
            ans:"B",
            exp:"眼睛低估錯誤，量化才能真實反映品質。",
            exp_en:"The eye underestimates errors; metrics are the only honest signal."},
          {type:"single",
            stem:"TrackMate 與其他工具的整合優勢？",
            stem_en:"Integration strength of TrackMate?",
            A:"可直接整合 Cellpose / StarDist / Weka 作為 detector", A_en:"Directly integrates Cellpose / StarDist / Weka as detector",
            B:"只能用內建 LoG", B_en:"Only built-in LoG",
            C:"純 Python", C_en:"Python only",
            D:"需付費", D_en:"Paid software",
            ans:"A",
            exp:"TrackMate 7 將 Cellpose、StarDist 等納為 detector，互動 GUI 仍可用。",
            exp_en:"TrackMate 7 plugs Cellpose / StarDist / Weka in as detectors while keeping its GUI."},
          {type:"single",
            stem:"亞細胞單分子追蹤 (SPT) 最常見的 Python 工具？",
            stem_en:"Most common Python tool for single-particle tracking (SPT)?",
            A:"TrackPy", A_en:"TrackPy",
            B:"BWA", B_en:"BWA",
            C:"Cellpose", C_en:"Cellpose",
            D:"QuPath", D_en:"QuPath",
            ans:"A",
            exp:"TrackPy 是 Crocker-Grier SPT 演算法的 Python 實作。",
            exp_en:"TrackPy is the Python implementation of the Crocker-Grier SPT algorithm."},
          {type:"tf",
            stem:"是非題：偵測有分裂事件時，用純 Kalman 也能精準處理。",
            stem_en:"True/False: Pure Kalman handles mitotic events accurately.",
            ans:"F",
            exp:"純 Kalman 不模型化 division，會在分裂處製造 ID switch；改用 TrackMate/btrack/Trackastra。",
            exp_en:"Pure Kalman does not model division and produces ID switches at mitosis; use TrackMate/btrack/Trackastra."}
        ],
        "Step 9：量化與特徵 (Quantification)": [
          {type:"single",
            stem:"Pearson r=0.95 但兩通道背景都偏高，最該做？",
            stem_en:"Pearson r=0.95 but both channels have high background — top priority?",
            A:"扣背景，並用 Costes 隨機化檢定", A_en:"Subtract background and run Costes randomization",
            B:"換更高 NA 物鏡", B_en:"Higher NA objective",
            C:"接受結果", C_en:"Accept the result",
            D:"用 8-bit 重算", D_en:"Recompute in 8-bit",
            ans:"A",
            exp:"Pearson 對背景偏移極為敏感，必須先校正並做隨機 null 比較。",
            exp_en:"Pearson is very sensitive to background offset; subtract and compare to a random null."},
          {type:"single",
            stem:"什麼是 Manders' M1？",
            stem_en:"What is Manders' M1?",
            A:"ch2 正樣本中的 ch1 強度比例", A_en:"Fraction of ch1 intensity overlapping with positive ch2",
            B:"純背景值", B_en:"Pure background",
            C:"Otsu 閾值", C_en:"Otsu threshold",
            D:"細胞數量", D_en:"Cell count",
            ans:"A",
            exp:"M1 = (有 ch2 信號區域的 ch1 強度) / (全部 ch1 強度)。",
            exp_en:"M1 = (ch1 intensity in ch2-positive region) / (total ch1 intensity)."},
          {type:"single",
            stem:"Haralick texture 跨樣本不可比的主因？",
            stem_en:"Why are Haralick texture values often non-comparable across samples?",
            A:"灰階級數量化不一致", A_en:"Inconsistent grey-level quantization",
            B:"細胞太多", B_en:"Too many cells",
            C:"沒有 GPU", C_en:"No GPU",
            D:"影像太亮", D_en:"Image too bright",
            ans:"A",
            exp:"GLCM 對 levels 高度敏感，要統一量化才能比較。",
            exp_en:"GLCM is highly sensitive to the number of grey levels — match it across samples."},
          {type:"single",
            stem:"regionprops 的 centroid 順序？",
            stem_en:"regionprops centroid order?",
            A:"(x, y)", A_en:"(x, y)",
            B:"(row, col) = (y, x)", B_en:"(row, col) = (y, x)",
            C:"(z, y, x)", C_en:"(z, y, x)",
            D:"視 numpy 設定", D_en:"Depends on numpy",
            ans:"B",
            exp:"scikit-image 用 numpy 慣例 (row, col)。",
            exp_en:"scikit-image uses numpy's (row, col) convention."},
          {type:"multi",
            stem:"以下哪些是形態學特徵？（多選）",
            stem_en:"Which are morphology features? (Multiple)",
            A:"area", A_en:"area",
            B:"eccentricity", B_en:"eccentricity",
            C:"solidity", C_en:"solidity",
            D:"mean intensity", D_en:"mean intensity",
            ans:["A","B","C"],
            exp:"mean intensity 是強度特徵。其餘是形態。",
            exp_en:"mean intensity is an intensity feature; the rest are morphology."},
          {type:"single",
            stem:"PyRadiomics 主要特徵類別？",
            stem_en:"Main PyRadiomics feature classes?",
            A:"shape / first-order / GLCM / GLRLM / GLSZM / NGTDM / wavelet", A_en:"shape / first-order / GLCM / GLRLM / GLSZM / NGTDM / wavelet",
            B:"只有 GLCM", B_en:"GLCM only",
            C:"只有 shape", C_en:"shape only",
            D:"只有 wavelet", D_en:"wavelet only",
            ans:"A",
            exp:"PyRadiomics 符合 IBSI 標準，提供完整 radiomics 特徵集。",
            exp_en:"PyRadiomics is IBSI-compliant and offers the full radiomics feature set."},
          {type:"single",
            stem:"object-based colocalization 的優勢？",
            stem_en:"Advantage of object-based colocalization?",
            A:"避免像素級背景偏移，直接量「胞器級重疊」", A_en:"Avoids pixel-level background bias by measuring 'organelle-level overlap'",
            B:"必須用 8-bit", B_en:"Requires 8-bit",
            C:"沒有優勢", C_en:"No advantage",
            D:"自動配置 GPU", D_en:"Auto GPU",
            ans:"A",
            exp:"對於粒線體 / 囊泡這類有明確邊界的胞器，object-based 比像素級更合理。",
            exp_en:"For organelles with clear boundaries (mitochondria, vesicles), object-based is more meaningful than pixel-level."},
          {type:"single",
            stem:"Costes 隨機化檢定的目的？",
            stem_en:"Purpose of the Costes randomization test?",
            A:"檢驗共定位是否顯著高於隨機 null", A_en:"Test whether colocalization is significantly above a random null",
            B:"自動分割", B_en:"Auto segmentation",
            C:"GPU 排程", C_en:"GPU scheduling",
            D:"訓練 DL", D_en:"Train DL",
            ans:"A",
            exp:"Costes 把一通道區塊洗牌，得到 null 分佈，看實測 r 是否落於高端。",
            exp_en:"Costes scrambles one channel in blocks to build a null and checks if observed r sits at the high end."},
          {type:"single",
            stem:"per-cell features → per-well 聚合，最穩健的統計量？",
            stem_en:"Aggregating per-cell features to per-well — most robust statistic?",
            A:"median + MAD", A_en:"median + MAD",
            B:"mean + std", B_en:"mean + std",
            C:"max", C_en:"max",
            D:"sum", D_en:"sum",
            ans:"A",
            exp:"CP 表型分佈重尾，median + MAD 比 mean + std 穩健。",
            exp_en:"CP distributions are heavy-tailed; median + MAD is more robust than mean + std."},
          {type:"tf",
            stem:"是非題：可以對「未濾波」與「濾波後」的影像混合做 quantitative 比較。",
            stem_en:"True/False: It's fine to mix unfiltered and filtered images in quantitative comparisons.",
            ans:"F",
            exp:"必須對所有條件用一致濾波，否則差異被處理流程而非生物學決定。",
            exp_en:"Apply identical filtering across all conditions; otherwise differences reflect processing, not biology."}
        ]
      },
      "進階主題": {
        "Advanced：3D 與多維分析": [
          {type:"single",
            stem:"XY=0.2 µm、Z=1.0 µm 的 confocal，Cellpose 3D 該怎麼設？",
            stem_en:"Confocal with XY=0.2 µm, Z=1.0 µm — Cellpose 3D setting?",
            A:"anisotropy=5", A_en:"anisotropy=5",
            B:"anisotropy=0.2", B_en:"anisotropy=0.2",
            C:"不需設", C_en:"No setting needed",
            D:"isotropy=5", D_en:"isotropy=5",
            ans:"A",
            exp:"anisotropy = Z spacing / XY spacing = 1.0/0.2 = 5。",
            exp_en:"anisotropy = Z spacing / XY spacing = 1.0/0.2 = 5."},
          {type:"single",
            stem:"800 GB light-sheet 資料最該怎麼處理？",
            stem_en:"How to handle 800 GB light-sheet data?",
            A:"用 OME-Zarr / N5 + dask 惰性處理", A_en:"OME-Zarr / N5 + dask lazy processing",
            B:"tifffile.imread 一次載入", B_en:"tifffile.imread all at once",
            C:"買 1TB RAM", C_en:"Buy 1 TB RAM",
            D:"轉 8-bit", D_en:"Convert to 8-bit",
            ans:"A",
            exp:"分塊存取 + 惰性運算是 TB 級資料事實標準。",
            exp_en:"Chunked storage + lazy computation is the de facto solution for TB-scale data."},
          {type:"single",
            stem:"napari 最大優勢？", stem_en:"napari's biggest strength?",
            A:"Python 原生 N-D viewer，與 ML / Cellpose / StarDist 緊密整合", A_en:"Python-native N-D viewer, tight ML / Cellpose / StarDist integration",
            B:"取代 Jupyter", B_en:"Replaces Jupyter",
            C:"純 C 語言", C_en:"Pure C",
            D:"不支援 3D", D_en:"No 3D support",
            ans:"A",
            exp:"napari 是 Python bioimage 生態的互動中樞，最強於 ML 整合與 plugin 開發。",
            exp_en:"napari is the Python bioimage hub — best for ML integration and plugin authoring."},
          {type:"single",
            stem:"密集相黏 3D 組織分割首選？",
            stem_en:"Best segmentation for dense touching 3D tissue?",
            A:"真正 3D 分割 (Cellpose 3D do_3D=True 或 StarDist 3D)", A_en:"True 3D segmentation (Cellpose 3D do_3D=True or StarDist 3D)",
            B:"逐片 2D 不拼接", B_en:"Per-slice 2D, no stitching",
            C:"Otsu", C_en:"Otsu",
            D:"壓平 Z 後 2D", D_en:"Flatten Z then 2D",
            ans:"A",
            exp:"密集 3D 必須真正 3D 才能解 z 方向的歧義。",
            exp_en:"Dense 3D needs true 3D models to resolve Z ambiguity."},
          {type:"single",
            stem:"PlantSeg 設計用途？", stem_en:"PlantSeg is designed for?",
            A:"植物 / 動物組織 3D 細胞邊界分割（DL + graph partitioning）", A_en:"Plant/animal 3D cell-boundary segmentation (DL + graph partitioning)",
            B:"DAPI 核分割", B_en:"DAPI nucleus segmentation",
            C:"WSI 分類", C_en:"WSI classification",
            D:"染色正規化", D_en:"Stain normalization",
            ans:"A",
            exp:"PlantSeg 是 3D 邊界式分割工具，植物器官 / 胚胎研究常見。",
            exp_en:"PlantSeg performs 3D boundary-based segmentation — common in plant organs and embryos."},
          {type:"multi",
            stem:"哪些屬於 napari 原生 layer 類型？（多選）",
            stem_en:"Which are native napari layer types? (Multiple)",
            A:"Image", A_en:"Image", B:"Labels", B_en:"Labels",
            C:"Points", C_en:"Points", D:"Audio", D_en:"Audio",
            ans:["A","B","C"],
            exp:"napari 支援 image/labels/points/shapes/vectors/tracks/surfaces，不支援 audio。",
            exp_en:"napari supports image/labels/points/shapes/vectors/tracks/surfaces; not audio."},
          {type:"single",
            stem:"什麼時候用 2D + IoU stitch 而非真 3D？",
            stem_en:"When to use 2D + IoU stitch instead of true 3D?",
            A:"稀疏物件、速度優先", A_en:"Sparse objects, prioritize speed",
            B:"密集相黏組織", B_en:"Dense touching tissue",
            C:"完全無 Z 資訊時", C_en:"When no Z info exists",
            D:"必須用 GPU 時", D_en:"When GPU is mandatory",
            ans:"A",
            exp:"稀疏 / 邊界清楚的物件用 2D + stitch 就很好，更快。",
            exp_en:"For sparse, well-separated objects 2D + stitch is fast and sufficient."},
          {type:"tf",
            stem:"是非題：3D 形態學特徵直接用 voxel count 即可，不需 voxel size。",
            stem_en:"True/False: 3D morphology features can use voxel count directly without voxel size.",
            ans:"F",
            exp:"voxel size 不同會讓「體積、表面積、球度」失去物理意義。",
            exp_en:"Without voxel size, volume / surface area / sphericity lose physical meaning."},
          {type:"single",
            stem:"BigDataViewer / mobie 用來做什麼？",
            stem_en:"BigDataViewer / mobie are for?",
            A:"TB 級 N-D 影像的互動視覺化", A_en:"Interactive visualization of TB-scale N-D images",
            B:"DL 訓練", B_en:"DL training",
            C:"PCA 降維", C_en:"PCA",
            D:"資料庫管理", D_en:"Database management",
            ans:"A",
            exp:"BigDataViewer 是 Fiji 系列 TB 影像視覺化標準，mobie 用於分享與探索。",
            exp_en:"BigDataViewer is the Fiji-ecosystem standard for TB-scale viewing; mobie is for sharing/exploration."},
          {type:"single",
            stem:"dask-image 的主要用途？",
            stem_en:"Main use of dask-image?",
            A:"分塊、惰性、平行的影像處理", A_en:"Chunked, lazy, parallel image processing",
            B:"取代 GPU", B_en:"Replace GPU",
            C:"DL 訓練", C_en:"DL training",
            D:"壓縮影像", D_en:"Compress images",
            ans:"A",
            exp:"dask-image 是 dask 上的影像版 ndimage，適合大資料 out-of-core 處理。",
            exp_en:"dask-image is dask's ndimage equivalent for out-of-core processing."}
        ],
        "Advanced：高內涵分析 (HCS)": [
          {type:"single",
            stem:"96-well 結果顯示「最外圈 well 都是 hit」，最可能？",
            stem_en:"96-well screen says 'all outer wells are hits' — most likely?",
            A:"Edge effect (外圈蒸發 / 溫度差)", A_en:"Edge effect (outer wells dry out / hotter)",
            B:"標靶位置敏感", B_en:"Spatially specific target",
            C:"DL 模型錯誤", C_en:"DL model error",
            D:"染色不均", D_en:"Uneven staining",
            ans:"A",
            exp:"邊緣 well 的蒸發、孵箱位置造成系統性偏差，是 HCS 經典陷阱。",
            exp_en:"Edge wells suffer evaporation / temperature variation — a canonical HCS trap."},
          {type:"single",
            stem:"per-cell 聚合到 per-well 的最佳統計？",
            stem_en:"Best statistic to aggregate per-cell to per-well?",
            A:"median + MAD", A_en:"median + MAD",
            B:"mean + std", B_en:"mean + std",
            C:"sum", C_en:"sum",
            D:"max", D_en:"max",
            ans:"A",
            exp:"CP 表型分佈重尾，robust 統計更可靠。",
            exp_en:"CP distributions are heavy-tailed; robust statistics are safer."},
          {type:"single",
            stem:"Percent-replicating 衡量？",
            stem_en:"Percent-replicating measures?",
            A:"複製品重複比例", A_en:"Fraction of duplicates",
            B:"同擾動的 replicate 相似度顯著高於隨機 null 的比例", B_en:"Fraction of perturbations whose replicate similarity beats a random null",
            C:"DNA 複製率", C_en:"DNA replication rate",
            D:"plate 數量", D_en:"Number of plates",
            ans:"B",
            exp:"是 assay reproducibility 的事實標準指標。",
            exp_en:"The canonical assay-reproducibility metric."},
          {type:"single",
            stem:"Cell Painting 通常用幾個通道？",
            stem_en:"How many channels in Cell Painting?",
            A:"5 個通道（DNA、RNA、ER、Golgi/PM、F-actin、Mito，其中 SYTO14 + Phalloidin 在不同 channel 拍攝視 protocol）", A_en:"5 channels covering DNA, RNA, ER, Golgi/PM, F-actin, Mito",
            B:"1 個", B_en:"1",
            C:"50 個", C_en:"50",
            D:"100 個", D_en:"100",
            ans:"A",
            exp:"標準 Cell Painting 是 6 染料 / 5 通道（兩個染料拍同一 channel）。",
            exp_en:"Standard Cell Painting uses 6 dyes across 5 channels (two dyes share a channel)."},
          {type:"single",
            stem:"pycytominer 主要功能？",
            stem_en:"Main function of pycytominer?",
            A:"表型 profile 的正規化、特徵選擇、聚合", A_en:"Profile normalization, feature selection, aggregation",
            B:"細胞分割", B_en:"Cell segmentation",
            C:"DL 訓練", C_en:"DL training",
            D:"WSI 拼接", D_en:"WSI stitching",
            ans:"A",
            exp:"pycytominer 是 Broad 的 HCS 後處理工具事實標準。",
            exp_en:"pycytominer is the Broad's de facto HCS post-processing tool."},
          {type:"single",
            stem:"DeepProfiler 提供什麼？",
            stem_en:"What does DeepProfiler provide?",
            A:"DL 特徵嵌入取代 CP 手工特徵", A_en:"DL feature embeddings instead of CP hand-crafted features",
            B:"WSI 拼接", B_en:"WSI stitching",
            C:"染色正規化", C_en:"Stain normalization",
            D:"自動實驗設計", D_en:"Auto experiment design",
            ans:"A",
            exp:"DeepProfiler 用預訓練 CNN 提 embedding，較傳統 CP 特徵更穩健。",
            exp_en:"DeepProfiler uses pretrained CNNs for embeddings — often more robust than CP features."},
          {type:"multi",
            stem:"以下哪些是常見 plate 效應？（多選）",
            stem_en:"Which are common plate effects? (Multiple)",
            A:"Edge effect", A_en:"Edge effect",
            B:"Row/column gradient", B_en:"Row/column gradient",
            C:"Plate-to-plate variation", C_en:"Plate-to-plate variation",
            D:"GPU 排程", D_en:"GPU scheduling",
            ans:["A","B","C"],
            exp:"前三者皆為實驗系統偏差。GPU 是分析架構，不是 plate 效應。",
            exp_en:"First three are experimental biases; GPU is an analysis-side concern."},
          {type:"single",
            stem:"CellProfiler 4 跑 plate 規模批次的推薦方式？",
            stem_en:"Recommended way to run CellProfiler 4 at plate-scale?",
            A:"headless / CLI 上叢集", A_en:"headless / CLI on cluster",
            B:"GUI 一張一張", B_en:"GUI one by one",
            C:"純 R", C_en:"Pure R",
            D:"純 Excel", D_en:"Pure Excel",
            ans:"A",
            exp:"<code>cellprofiler --run-headless</code> 可在 HPC / 雲端批次。",
            exp_en:"<code>cellprofiler --run-headless</code> runs on HPC / cloud."},
          {type:"single",
            stem:"JUMP-CP 是什麼？", stem_en:"What is JUMP-CP?",
            A:"3M+ Cell Painting 影像 + 配對化合物 / 遺傳擾動的公開資料集", A_en:"3M+ Cell Painting images with paired chemical / genetic perturbations",
            B:"GPU 公司", B_en:"A GPU company",
            C:"資料庫管理工具", C_en:"DB management tool",
            D:"Fiji plugin", D_en:"Fiji plugin",
            ans:"A",
            exp:"JUMP-CP (Chandrasekaran 2024) 是世界級 HCS 公開資源。",
            exp_en:"JUMP-CP (Chandrasekaran 2024) is the world-class public HCS resource."},
          {type:"tf",
            stem:"是非題：HCS 不需正規化即可比較不同 plate 的結果。",
            stem_en:"True/False: HCS doesn't need normalization to compare across plates.",
            ans:"F",
            exp:"必須做 plate-wise 正規化（例如對 DMSO control 的 robust z-score）。",
            exp_en:"Plate-wise normalization (e.g., robust z to DMSO controls) is mandatory."}
        ],
        "Advanced：數位病理 (Pathology)": [
          {type:"single",
            stem:"跨醫院 H&amp;E DL 部署的首要前處理？",
            stem_en:"Top preprocessing for cross-hospital H&E DL?",
            A:"染色正規化 (Macenko / Vahadane / StainGAN)", A_en:"Stain normalization (Macenko / Vahadane / StainGAN)",
            B:"轉 8-bit", B_en:"Convert to 8-bit",
            C:"降低解析度", C_en:"Downscale",
            D:"不需要", D_en:"Not needed",
            ans:"A",
            exp:"跨機構顏色差異是 H&E 模型最大殺手。",
            exp_en:"Cross-site colour drift is the #1 killer of H&E models."},
          {type:"single",
            stem:"UNI / Virchow 預期 ~0.5 µm/px。直接用 40× (0.25 µm/px)？",
            stem_en:"UNI / Virchow expect ~0.5 µm/px. Use 40× (0.25 µm/px) directly?",
            A:"不報錯但效能 silently 下降", A_en:"No error, but performance silently drops",
            B:"自動修正", B_en:"Auto-corrects",
            C:"變更準", C_en:"More accurate",
            D:"報錯", D_en:"Throws an error",
            ans:"A",
            exp:"MPP 錯誤是 WSI 模型常見 silent failure，務必對齊預期。",
            exp_en:"Wrong MPP is a classic silent failure — always match the expected MPP."},
          {type:"single",
            stem:"CLAM 等 MIL 適合？", stem_en:"MIL methods like CLAM are suited to?",
            A:"只有 slide-level 標籤 (無 patch 級標註)", A_en:"Slide-level labels only (no patch annotation)",
            B:"完全 pixel-level annotated 資料", B_en:"Pixel-level annotated data",
            C:"無標籤", C_en:"No labels",
            D:"純分割", D_en:"Pure segmentation",
            ans:"A",
            exp:"MIL 為 weakly-supervised slide-level 分類設計，正是「只有 slide 標籤」的情境。",
            exp_en:"MIL is designed for weakly-supervised slide-level classification — exactly the slide-labels-only case."},
          {type:"single",
            stem:"Macenko 算法在什麼空間找 stain vector？",
            stem_en:"In which space does Macenko find stain vectors?",
            A:"Optical Density (OD) 空間", A_en:"Optical Density (OD) space",
            B:"RGB", B_en:"RGB",
            C:"YUV", C_en:"YUV",
            D:"FFT", D_en:"FFT",
            ans:"A",
            exp:"OD = -log10(I/I0)。stain 在 OD 空間更線性，方便分離 H 與 E 向量。",
            exp_en:"OD = -log10(I/I0). Stains are more linear in OD space, easing H/E vector separation."},
          {type:"single",
            stem:"WSI 處理為什麼要 tile？",
            stem_en:"Why tile WSIs for processing?",
            A:"Giga-pixel 無法整檔載入；金字塔分塊存取最有效", A_en:"Gigapixel can't fit in RAM; pyramidal tiled access is the efficient way",
            B:"美觀考量", B_en:"Aesthetic",
            C:"DL 模型只能讀 256×256", C_en:"DL models only read 256×256",
            D:"OpenSlide 強制要求", D_en:"OpenSlide forces it",
            ans:"A",
            exp:"WSI 太大不能整檔載入，金字塔 + tile 是事實標準。",
            exp_en:"WSI is too large to load whole; pyramid + tile is the de facto pattern."},
          {type:"single",
            stem:"HoVer-Net 同時做什麼？", stem_en:"What does HoVer-Net do simultaneously?",
            A:"核分割 + 核類型分類", A_en:"Nucleus segmentation + classification",
            B:"WSI 拼接", B_en:"WSI stitching",
            C:"染色正規化", C_en:"Stain normalization",
            D:"細胞通訊", D_en:"Cell communication",
            ans:"A",
            exp:"HoVer-Net 同時輸出 instance mask 與分類標籤（5 個 PanNuke 類）。",
            exp_en:"HoVer-Net outputs instance masks AND classification labels (5 PanNuke classes)."},
          {type:"multi",
            stem:"以下哪些是染色正規化方法？（多選）",
            stem_en:"Which are stain normalization methods? (Multiple)",
            A:"Macenko", A_en:"Macenko",
            B:"Reinhard", B_en:"Reinhard",
            C:"Vahadane", C_en:"Vahadane",
            D:"StainGAN", D_en:"StainGAN",
            ans:["A","B","C","D"],
            exp:"四者都是 stain normalization 主流方法（傳統三種 + DL）。",
            exp_en:"All four are mainstream stain normalization methods (three classical + DL)."},
          {type:"single",
            stem:"QuPath 主要腳本語言？", stem_en:"Primary scripting language in QuPath?",
            A:"Groovy", A_en:"Groovy",
            B:"Python", B_en:"Python",
            C:"R", C_en:"R",
            D:"Bash", D_en:"Bash",
            ans:"A",
            exp:"QuPath 用 Groovy（JVM）腳本。Python 可透過 paquo / py4j 介接但不是內建。",
            exp_en:"QuPath uses Groovy (JVM). Python via paquo / py4j is possible but not built-in."},
          {type:"single",
            stem:"TIA Toolbox 與 PathML 的差異？",
            stem_en:"Difference between TIA Toolbox and PathML?",
            A:"TIA Toolbox 是 University of Warwick 的 WSI 完整 pipeline；PathML 是 Dana-Farber/Cornell 統一 brightfield + IF + spatial omics 的 API", A_en:"TIA Toolbox: Warwick's end-to-end WSI pipeline; PathML: Dana-Farber/Cornell unified brightfield + IF + spatial omics API",
            B:"完全一樣", B_en:"Identical",
            C:"TIA 是 GUI、PathML 是 CLI", C_en:"TIA is GUI, PathML is CLI",
            D:"PathML 取代了 TIA", D_en:"PathML replaced TIA",
            ans:"A",
            exp:"兩者皆是優秀的 WSI Python library，但定位略有不同。",
            exp_en:"Both are excellent Python WSI libraries with different scopes."},
          {type:"tf",
            stem:"是非題：在 H&E DL 部署上，颜色正規化可以省略。",
            stem_en:"True/False: Stain normalization can be skipped in H&E DL deployment.",
            ans:"F",
            exp:"跨機構顏色變異會嚴重損害模型泛化，必須做。",
            exp_en:"Cross-site colour variance severely hurts generalization; it's mandatory."}
        ],
        "Advanced：工具比較與整合": [
          {type:"single",
            stem:"無 Python 背景的生物實驗室做 96-well 篩選，最務實組合？",
            stem_en:"Non-Python lab running a 96-well screen — pragmatic stack?",
            A:"Fiji + CellProfiler + QuPath (皆 GUI)", A_en:"Fiji + CellProfiler + QuPath (all GUI)",
            B:"純 PyTorch", B_en:"Pure PyTorch",
            C:"純 napari notebook", C_en:"Pure napari notebook",
            D:"買商業軟體", D_en:"Buy commercial software",
            ans:"A",
            exp:"無 Python 背景時 GUI 組合最務實。",
            exp_en:"For non-Python labs, a GUI stack is the pragmatic choice."},
          {type:"single",
            stem:"想讓模型在 Fiji、ilastik、QuPath 都能用，最佳做法？",
            stem_en:"To make a model usable in Fiji, ilastik, and QuPath?",
            A:"上傳到 BioImage Model Zoo (跨工具標準格式)", A_en:"Upload to BioImage Model Zoo (cross-tool standard format)",
            B:"各別重訓三次", B_en:"Retrain three times",
            C:"只發 PyTorch checkpoint", C_en:"Just publish PyTorch checkpoint",
            D:"不可能跨工具", D_en:"Cross-tool is impossible",
            ans:"A",
            exp:"BioImage Model Zoo 就是為跨工具模型分享而生。",
            exp_en:"The Model Zoo exists exactly for cross-tool model sharing."},
          {type:"single",
            stem:"論文級可重現性最完整做法？",
            stem_en:"Most complete paper-level reproducibility?",
            A:"Snakemake / Nextflow + conda lock + Docker + 範例資料 + Zenodo DOI", A_en:"Snakemake/Nextflow + conda lock + Docker + example data + Zenodo DOI",
            B:"上傳 PowerPoint flowchart", B_en:"Upload PowerPoint flowchart",
            C:"只放 notebook", C_en:"Notebook only",
            D:"在 README 列指令", D_en:"List commands in README",
            ans:"A",
            exp:"工作流引擎 + 鎖死環境 + 容器 + 範例資料 + 永久 DOI 是完整 reproducibility 配方。",
            exp_en:"Workflow engine + locked env + container + example data + persistent DOI is the complete recipe."},
          {type:"single",
            stem:"何時最該離開 Fiji 改用 Python？",
            stem_en:"When should you leave Fiji for Python?",
            A:"需要 cluster / 雲端 / git / DL 訓練 / 與表達資料整合時", A_en:"When you need cluster / cloud / git / DL training / multi-modal integration",
            B:"永遠不用離開", B_en:"Never leave",
            C:"只有看圖時", C_en:"Only for viewing",
            D:"GUI 已死", D_en:"GUI is dead",
            ans:"A",
            exp:"Fiji 對單一影像探索無敵，但叢集 / ML / 跨資料整合屬於 Python 強項。",
            exp_en:"Fiji excels at single-image exploration; cluster / ML / multi-data live in Python."},
          {type:"single",
            stem:"image.sc 是？", stem_en:"What is image.sc?",
            A:"bioimage 工具的共同論壇 (Fiji/napari/CellProfiler/QuPath 開發者都在)", A_en:"Shared forum for bioimage tools (Fiji/napari/CellProfiler/QuPath devs all there)",
            B:"GitHub clone", B_en:"GitHub clone",
            C:"商業 SaaS", C_en:"Commercial SaaS",
            D:"Fiji 競品", D_en:"A Fiji competitor",
            ans:"A",
            exp:"image.sc 是 bioimage 社群的中央問答區。",
            exp_en:"image.sc is the central Q&A hub of the bioimage community."},
          {type:"multi",
            stem:"以下哪些屬於 reproducibility 工具？（多選）",
            stem_en:"Which are reproducibility tools? (Multiple)",
            A:"Snakemake", A_en:"Snakemake",
            B:"Nextflow", B_en:"Nextflow",
            C:"Docker / Apptainer", C_en:"Docker / Apptainer",
            D:"conda / pixi / uv lockfile", D_en:"conda / pixi / uv lockfile",
            ans:["A","B","C","D"],
            exp:"四者都用於可重現工作流的不同層面。",
            exp_en:"All four address different layers of reproducible workflows."},
          {type:"single",
            stem:"ilastik 主要強項？", stem_en:"ilastik's main strength?",
            A:"少量稀疏標註 + Random Forest 互動學習", A_en:"Sparse annotation + interactive Random Forest learning",
            B:"GPU 訓練 ResNet", B_en:"GPU-train ResNet",
            C:"WSI 拼接", C_en:"WSI stitching",
            D:"染色正規化", D_en:"Stain normalization",
            ans:"A",
            exp:"ilastik 為「稀疏標註、像素分類、追蹤」工作流設計，與其他工具互補。",
            exp_en:"ilastik is designed for sparse-annotation pixel classification & tracking — complementing others."},
          {type:"single",
            stem:"BAND 是什麼？", stem_en:"What is BAND?",
            A:"雲端啟動的 bioimage 桌面，免安裝", A_en:"Cloud-launched bioimage desktop, no install",
            B:"染色技術", B_en:"Staining technique",
            C:"GPU 雲", C_en:"GPU cloud",
            D:"資料庫", D_en:"Database",
            ans:"A",
            exp:"BAND 由 EMBL-EBI 提供，瀏覽器啟動完整 bioimage 桌面環境。",
            exp_en:"BAND (EMBL-EBI) launches a full bioimage desktop from a browser."},
          {type:"tf",
            stem:"是非題：發 Fiji macro 時不必寫明 Fiji 版本與 plugin update site，反正讀者會自己裝。",
            stem_en:"True/False: When publishing a Fiji macro, you don't need to specify Fiji version and plugin update sites.",
            ans:"F",
            exp:"Fiji macro 跨版本常 silent break；要明確標示版本與 update site。",
            exp_en:"Fiji macros silently break across versions; specify version and update sites explicitly."},
          {type:"single",
            stem:"BioImage Archive (BIA) 之於影像，如同 ___ 之於序列",
            stem_en:"BioImage Archive (BIA) is to images as ___ is to sequences",
            A:"GEO / SRA", A_en:"GEO / SRA",
            B:"PyPI", B_en:"PyPI",
            C:"Docker Hub", C_en:"Docker Hub",
            D:"napari hub", D_en:"napari hub",
            ans:"A",
            exp:"BIA 是 EMBL-EBI 的影像公共資料庫，類比 GEO / SRA 之於序列。",
            exp_en:"BIA is EMBL-EBI's public image repository — analogous to GEO/SRA for sequences."}
        ]
      }
    }
  }
};
